// PAGE ELEMENT VARIABLES


// DISPLAY THE DATE USING MOMENT
$("#currentDay").text(moment().format("MMM Do, YYYY h:mm a"));
// SCRIPT THAT CHANGES FORM COLOR BASED ON TIME


// LOCAL STORAGE FOR DATE ENTIRES TIED TO THE FORM BUTTONS